//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CantinaBill.ConexãoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Venda
    {
        public int idItem { get; set; }
        public int idVenda { get; set; }
        public int idProduto { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> Val_Un { get; set; }
        public Nullable<decimal> Valor_Total { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Venda Venda { get; set; }
    }
}
