//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CantinaBill.ConexãoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venda()
        {
            this.Item_Venda = new HashSet<Item_Venda>();
        }
    
        public int idVenda { get; set; }
        public int idPessoa { get; set; }
        public Nullable<System.DateTime> Data_venda { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public Nullable<decimal> Taxa_Entrega { get; set; }
        public Nullable<decimal> Valor_Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Venda> Item_Venda { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
